export {default as Header} from './header/Header'
export {default as CollectNFTs} from './collect-nft/CollectNFTs'
export {default as TopCreators} from './top-creators/TopCreators'
export {default as Newsletter} from './newsletter/Newsletter'
export {default as NFTsCollections} from './nft-collections/NFTsCollections'
export {default as LatestBlog} from './latest-blog/LatestBlog'
export {default as Footer} from './footer/Footer'
export {default as Layout} from './Layout'