export {default as Homepage} from './Homepage'
export {default as Signup} from './Signup'
export {default as Login} from './Login'
export {default as About} from './About'
export {default as ContactUs} from './ContactUs'
export {default as NotFound} from './NotFound'